/*
Navicat MySQL Data Transfer

Source Server         : Local Server
Source Server Version : 50733
Source Host           : localhost:3306
Source Database       : vl_online

Target Server Type    : MYSQL
Target Server Version : 50733
File Encoding         : 65001

Date: 2022-07-29 08:54:52
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `products` (brand_id,name,category_id,qty_onhand)
-- ----------------------------
DROP TABLE IF EXISTS `products` (brand_id,name,category_id,qty_onhand);
CREATE TABLE `products` (brand_id,name,category_id,qty_onhand) (
  `brand_id` int(11) DEFAULT NULL,
  `name` varchar(89) CHARACTER SET utf8 DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `qty_onhand` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of mapping_data
-- ----------------------------
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('1', 'ALAIA Garance Phone Bag in Sable - Tan', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Shadow Lollipop 9.5cm Crystal Buckle [37]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Shadow Lollipop 9.5cm Crystal Buckle [38]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Glass PVC Pink [36,5]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Glass PVC Pink [37]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Glass PVC Pink [38]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Pump Glass PVC Pink [39]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [36,5]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [38,5]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [38]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('2', 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [39]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Shopping Phone Holder Logo White Croco', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Giant Haussmanian Gris', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Giant Black SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Giant Black SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Edge Black GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge Black GHW', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Regular Edge Black GHW', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Edge Grey (Gris) SHW', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Edge Grey (Gris) GHW', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge Grey (Gris) GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge Grey (Gris) SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Regular Edge Grey (Gris) SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge White Blanc SHW', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge White Blanc GHW', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Edge Mink SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Regular Edge Shinny Rose Des Sables AJ SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Anthracite GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Anthracite SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Black Shinny AJ RHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Black Matte RHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Black SHW', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Classic Black GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Classic Black GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Graffiti Black White RHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Clip M clutch/pochette in Navy Blue', '11', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Ville XXS Dark Taupe', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Neo Lift Bumbag Grey', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA BB Trifold Mini GHW Wallet', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA BB Women clutch in Croco Red Stamp', '4', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Cabas S Black Crinkle Leather', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Cabas S Grey Crinkle Leather', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Le Cagole XS Shoulder Crocodile Beige GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Le Cagole XS Shoulder Crocodile Lilac GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Le Cagole XS Shoulder Crocodile Black', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Le Cagole XS Shoulder Crocodile Pink', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Le Cagole XS Shoulder Crocodile White SHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Women Chunky Slide Sandals in Beige [35]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Women Chunky Slide Sandals in White [35]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Women Chunky Slide Sandals in White [36]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Track Rubber Sandal Pink/Black [38] insole 25cm', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Track Rubber Sandal Pink/Black [39]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Track Rubber Sandal Beige [40] insole 27cm', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Giant Card Case Rouge/Red', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Giant Card Case Black GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Giant Card Case Haussmanian GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Classic Card Case Anthracite GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Neo Classic Trifold wallet black GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Classic City Bifold Card', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Long Zippy Wallet Metallic Edge in Black GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Edge Mini Wallet Grey GHW', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Edge Mini Wallet Black GHW', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Asher Sneaker Black Leather [43]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Elsa with logo 5.5cm Heels Black Calf [36]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Elsa with logo 5.5cm Heels Black Calf [37]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Elsa with logo 5.5cm Heels Black Calf [39]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Women Mandye White Sneakers [36]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Women Mandye White Sneakers [36.5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Women Mandye White Sneakers [37]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('4', 'BALLY Women Mandye White Sneakers [37.5]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('5', 'BAO BAO ISSEY MIYAKE Prism Tote Bag in Blush Lucent', '14', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV The Chain Pouch in Black SHW Butter Calf SHW', '4', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie Caramel', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie Blaster Patent Leather', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie Blaster', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie in Thunder Grey', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie Black', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie in Chalk', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie in Fountain', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV Mini Jodie in Raintree', '2', '4');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('7', 'BOYY BOBBY 18 T-Rex', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('7', 'BOY BOBBY 18 Alll Black', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('7', 'BOY BOBBY 18 Meringue', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('7', 'BOY BOBBY 23 Gold Buckle Tote Bag', '2', '3');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Lola Small Lambskin Camel Shoulder Bag', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Knitted Check Olympia Pouch Birch Brown', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Vintage Check Bucket Hat [S]', '3', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Vintage Check Bucket Hat [M]', '3', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Vintage Check Bucket Hat [L]', '3', '-1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Reversible Check Bucket Hat Yellow/Brown [M]', '3', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('8', 'BURBERRY Vintage Check Bifold Wallet Archive Beige', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Bucket Hat in Vinyl Black [M]', '3', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Bucket Cotton Hat in Black [L]', '3', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Monogram Bucket Hat [S]', '3', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Nano Belt Bag Taupe', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Nano Belt Bag Grey', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Mini Vertical Cabas in Natural / Tan', '4', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Pico Belt Green Clay', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Small Strap Wallet Textured Leather in Peony Carmin', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Triomphe Canvas Small Drawstring Bag White', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL Ballerina Lambskin Flat Beige [36]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL Classicc Small Black Lamb GHW', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL 19 C19 Small White GHW', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL Boy Medium in Black Caviar GHW Size 25 x 15 x 9 cm', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL Boy Medium in Black Caviar RHW Size 25 x 15 x 9 cm', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'Chanel Gift Tote A La Plage', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('10', 'CHANEL Classic WOC Beige Caviar GHW with new CC strap chip', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('11', 'CHIARA FERRAGNI Eyelike Bucket Bag in Baby Pink', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Kate 70mm patent black pump [36,5]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Kate 70mm patent black pump [37]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Kate 70mm patent black pump [37,5]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Kate Heels 85mm Black Leather Pump [36]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Kate Heels 85mm Black Leather Pump [39]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Wallet Red All Card', '16', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Spikes Slide white studed [41]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Spikes Slide in Khaki [44]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('12', 'LOUBOUTIN Black Pool Flat Neoprene [42] insole 27cm', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('13', 'COACH Tabby Pillow Metallic Soft Gold', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('14', 'COMME DES GARCONS Girl X Disney limited edition Tshirt Minnie Ribbon [M]', '12', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('14', 'COMME DES GARCONS Girl X Disney limited edition Tshirt Minnie Ribbon [L]', '12', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Mizza Square Beige Multicolour 100% silk', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR CD Logo Belt Reversible Black-Navy 35mm GHW [80] 98cm', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR CD Logo Belt Reversible Black-Navy 35mm GHW [100] 116cm', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Saddle Belt 2cm Oblique [80]', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Saddle Belt 2cm Oblique [85]', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Saddle Trifold Compact Wallet Corda GHW', '16', '-1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Grey Oblique Leather Wallet', '16', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Saddle WoC Blue Oblique', '4', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Saddle WoC Black', '4', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Earring Tribales Pendant', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR J\'adior Earrings Tribales', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR J\'adior Pearl Tribales Earring', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Logo Gold Earring', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR D Lune Necklace in Gold Metal with Star and Love', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR D Lune Heart and Star Earring', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR J\'adior Star Earrings', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR J\'adior Gold Graphic Metal with Resin', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR J\'adior Chain Bracelet Antique Gold with Pearls', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR J\'adior Bracelet Logo Gold', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Wander Blue Oblique [36]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Earring Petit Gold-Finish Metal', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Granville Espadrille Toile De Jouy Grey [36]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Granville Espadrille Toile De Jouy Grey [38]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Deep Blue Toile De Jouy Rubber Sole (3cm) [36]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Deep Blue Toile De Jouy Rubber Sole (3cm) [39]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Granville Strippes Espadrilles Deep Blue [37]', '6', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Toile De Jouy Scarf Grey size 90 x 90cm', '1', '3');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Scarf/Shawl Silk Reversible in grey blue Oblique', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Twilly Toile De Jouy in Grey', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Twilly Logo Blue Stripes', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Club M1U Sunglasses Oblique Navy', '7', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Friendship Textile Bracelet Red / Black', '1', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Friendship Textile Bracelet Rose Des Vents', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Friendship Textile Bracelet Navy Oblique', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Friendship Bracelet Black Lime Embroidery', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Friendship Bracelet Green Pink Embroidery', '1', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Oblique Phone Holder', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal Gold-Tone Metallic [37]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [35,5]', '6', '4');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [38,5]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [39]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [39,5]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [40]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [40,5]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR 30 Montaigne Sunglasses Square White GHW - Beige Lense', '7', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'CHRISTIAN DIOR Dway Slides Black Embroidered Cotton and Shearling [39]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Revolution Slide Oblique Navy [35]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Revolution Slide Oblique Navy [36]', '6', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('16', 'FLP WoC Empire Green', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Logo WoC Grey', '4', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Pomodorino Mini Bag Brown', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Colibri Slingback Pump Velvet Mesh Heels 5cm Beige [37,5]', '6', '3');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'Fendi FF cotton Baseball Cap Military Green with Yellow Line Unisex', '3', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Bucket Hat FF Logo Jacquard Brown Leather [M]', '3', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI BTW Small Equator Multicolor', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI BTW Small Black', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI BTW Mini Camelia', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Tour Le Jour ( Preloved)', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI Continental Black Nappa Leather WoC GHW', '4', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('18', 'FURLA Bucket Costanza Nero', '2', '1');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('18', 'FURLA Mini Crossbody Bag Sand', '2', '3');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('19', 'GIVENCHY Antigona Mini Black Smooth Leather', '2', '2');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('19', 'GIVENCHY Antigona Small Grained Beige/Dune', '2', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('19', 'GIVENCHY Men Urban Street Sneakers in White [44]', '6', '0');
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('20', 'Goyard ST Louis PM Special Color Green', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('20', 'Goyard ST Louis PM Special Color Grey', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('20', 'Goyard ST Louis PM Special Color Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('20', 'Goyard ST Louis PM Special Color Black Tan', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Marmont Mini Backpack Round White Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Marmont Mini Backpack Round Black Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Marmont Mini Backpack Round Nude Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Mini Shoulder Bag Black SHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Mini Shoulder Bag White SHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Small Flap Nude SHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Small Flap Nude GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Small Camera Bag Porcelain Rose GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Enamel GG Marmont Small Camera Bag Emerald Blue GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Enamel GG Marmont Small Camera Bag Emerald White GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Marmont Large Pouch In Gold Tone Tan', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Mini Padlock Top Handle Beige Ebony Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Horsebit 1955 Mini /phone holder in Ivory', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Guccissima Dome Mini Top Handle Beige', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Guccissima Dome Mini Top Handle Grey', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Ophidia Dome Halfmoon Flower Flora / Floral', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Ophidia Small Flora with Chain shoulder Bag', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Rubber Dad Sandal White [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Rubber Dad Sandal White [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Rubber Platform Black (Runs Big) [35] insole 23', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Rubber Platform Black (Runs Big) [40] insole 28', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Rubber Platform White (Runs Big) [35] insole 23', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Women GG Espadrilles Mules in Black GHW [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Women GG Espadrilles Mules in Black GHW [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Women GG Espadrilles Mules in White GHW [35,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Women GG Canvas Linen Espadrille White Multicolor [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Women GG Double Sole Espadrilles in white GHW [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Supreme Canvas Ankle Boot Leather White Beige', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Princetown Horsebit Mules Beige [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Princetown Horsebit Mules Beige [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Princetown Horsebit Mules Beige [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Princetown GG Flora Mules [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Linen Espadrilles Multicolour', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI Marmont Platform Sandal Black Leather GHW [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Intarsia-Knit Cardigan Beige [S]', '9', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Intarsia-Knit Cardigan Beige [M]', '9', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Intarsia-Knit Cardigan [S]', '9', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Intarsia-Knit Cardigan [M]', '9', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('21', 'GUCCI GG Knit Cardigan Navy', '9', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('22', 'HERMES Sandal Egerie Jelly Vert Embrun [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('22', 'HERMES Oran Calfskin Sandal Gold [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('22', 'HERMES Oran Calfskin Sandal Gold [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('22', 'HERMES Eze Gold [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Black [M]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Black [L]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Black [XL]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Grey [M]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Grey [L]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Small Logo Jogger Pants in Grey [XL]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Logo Short Pants with Pocket Black [M]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Logo Short Pants with Pocket Black [L]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('23', 'BOSS Polo Curved Black Gold [L]', '10', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Grande Bambino in Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Mini Le Chiquito Calfskin White', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Mini Le Chiquito Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Moyen Chiquito in Honey/Beige', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Grand Chiquito White', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Moyen Noeud Chiquito White Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Chiquito Long in White', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Chiquito Long in Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Chiquito Moten wicker tote in Tan', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Gadjo Bucket Hat in off white [56]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Gadjo Bucket Hat in off white [58]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Gadjo Bucket Hat in khaki [58]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Gadjo Bucket Hat in black [56]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Gadjo Bucket Hat in black [58]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Bob Artichaut Bucket Cap Wide Brimmed Black [56]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('24', 'JACQUEMUS Le Chapeau Rattan Beach Hat', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('25', 'JIMMY CHOO Saeda 10cm Slingback Pumps Heels in Glitter Crystal Chain [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('25', 'JIMMY CHOO Saeda 10cm Slingback Pumps Heels in Glitter Crystal Chain [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('25', 'JIMMY CHOO Saeda Slingback Pumps in Gold Metallic Crystal Chain (10cm) [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('25', 'JIMMY CHOO Slingback Flat in Black [38,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL New Icon Neon Logo Top Handle with Removable Strap', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Rhinestone Tee Black [M]', '15', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Rhinestone Tee Black [L]', '15', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Rhinestone Tee White [M]', '15', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Rhinestone Tee White [L]', '15', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Rhinestone Jacket Soft White [M]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL New Icon Neo Bumbag', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Hoodie Jacket Stripe Rose [M]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Hoodie Jacket Stripe Marine [M]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Hoodie Jacket Stripe Marine [L]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Hoodie Jacket Stripe Black [M]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Hoodie Jacket Stripe Black [L]', '8', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Long Sleeve Black [S]', '12', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('26', 'KARL Long Sleeve White [XS]', '12', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Sport Little X TShirt Dress Purple [S]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Sport Little X TShirt Dress Purple [M]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Sport Little X TShirt Dress Purple [XL]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Black and White Monogram Cap', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Tiger Canvas Bebeboo Mini Backpack in Black Brown / Gold', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Bumbag Logo Cross Regular Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Clutch Cross Logo Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO K Logo Clutch Mint Colour', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Kampus Tiger Clutch Large in Black Leather', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Tiger Crest Trainer Men [42]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Tiger Campus Card Holder with Leather Strap', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Tiger Crest Trainer Men [43]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Tali Phone Holder in Black Leather with Removable Chain Strap', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Women Tiger Espadrilles in Navy blue/Red Canvas [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO K-Skate Tiger Slip On Sneakers Blush / Poudre [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO K-Skate Tiger Slip On Sneakers Blush / Poudre [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Jaquard Monogram Knitted Dress Deep Orange [XS]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Jaquard Monogram Knitted Dress Deep Orange [S]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Jaquard Monogram Knitted Dress Deep Orange [M]', '5', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Reversible Monogram/ White Bucket Hat [M]', '3', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Women Tiger Espadrilles in Black [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Women Tiger Espadrilles in Black [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Women Tiger Espadrilles in Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('28', 'LOEWE Small Rattan Basket Bag in Natural Tan Brown', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('28', 'LOEWE Small Rattan Basket Bag in Natural White', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('28', 'LOEWE Small Rattan Basket Bag in Natural Tan Navy', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Small Long Handle Navy', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Small Dessert', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Small Beige', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Small Beige Ivory', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Mini Dessert', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Small Bag Turtledove Metis', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Mini Turtledove', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Cuir Mini Sienna', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Paris Saint Tropez Bucket Bag Brown', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Paris Saint Tropez Bucket Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Paris Saint Tropez Bucket Bag Green', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Paris Saint Tropez Bucket Bag Maroon', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Filet White', '14', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Filet Black', '14', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Filet Top Handle Bag Navy', '14', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Mini Filet Sling Yellow', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Mini Filet Sling Blush', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Mini Filet Sling Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Mini Filet Sling Ecru', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Neo Mini Très Paris Navy', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Small City Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Long zip around Wallet Black White Leather', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Roseau Small Powder Crossbody Bag Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Essential Toile Tote Ecru', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Bagpack in Cognac', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [38,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [38,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Pump 70mm Black nude [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Pump 70mm Black nude [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Pump 70mm Black nude [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Flat /Mules Nude Blush [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('30', 'MALONE SOULIERS Maureen Flat /Mules Nude Blush [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('31', 'MANOLO BLAHNIK Hangisi 7cm mnude satin [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('31', 'MANOLO BLAHNIK Hangisi 7cm mnude satin [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('31', 'MANOLO BLAHNIK Hangisi heels 5cm in Royal Blue [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('31', 'MANOLO BLAHNIK Hangisi Pump 7cm in Black Glittered with White Crystal [35.5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Double Take Bag Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Snapshoot Top zip wallet Multicolour', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Colorblock Compact Zip Leather Wallet', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Snapshot Mini Wallet with Pocket Dusty Ruby Multi', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Small Snapshot DTM Camera Bag All Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Small Snapshot DTM Camera Bag Ink Grey', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS The Snapshot DTM Camera Bag White', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS The Snapshot WOC in Black/Red Multicolors', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS The Bold Open Wallet Black Leather', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Wallet Grained Leather Smoke Almond', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'Peanuts X Marc Jacobs The Snoopy Mini Tote Bag Green Multi', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS The Hot Shot DTM All Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Traveler Small Beige Canvas', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Traveler Large Beige Canvas', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Traveler Large Black Canvas', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Traveler Large Blue Shadow Canvas', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('32', 'MARC JACOBS Traveler Large Slate Green Canvas', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Mini Essential Crossbody Bag in Cognac', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Millie Flap Crossbody in Visetos', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Visetos Cognac Phone Holder with 6 card slot and zip', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Small Crossbody Pouch Trio Visetos Original Multi pochette Black/White/Cognac', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Klara Multifunction Phone Wallet Monogram Beige Leather', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Klara Multifunction Phone Wallet Monogram Black Leather', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Liz Shopper Reversible Medium Cognac', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Liz Shopper Reversible Medium Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('33', 'MCM Liz Shopper Reversible Medium White', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('34', 'MIU MIU Matelasse Shoulder Bag in Black GHW (with 2 strap)', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('35', 'MLB Front & Back Overfit New York Sweatshirt Black / Pink [XS]', '13', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('35', 'MLB Front & Back Overfit New York Sweatshirt Black / Pink [S]', '13', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('35', 'MLB Hobo Tote Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Sandal Slide White Black Embossed [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Platform Sandal Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Teddy Paint Tshirt White Woman White [XS]', '15', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Logo Ribbon and Leather in Black [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('37', 'PHILIP LIM Mini Odita Lattice Bag Leather Nude/White include Pouch', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Gabardine Crystal Embellished Slingback Pump [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Gabardine Crystal Embellished Slingback Pump [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Gabardine Crystal Embellished Slingback Pump [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Plexi Heel 7.5cm Silver [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition nylon vella shoulder bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition nylon vella shoulder bag Deserto', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2000 Tote Shoulder Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2000 Tote Shoulder Bag Glicine', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2005 in Black Saffiano', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2005 in Glicine', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2005 in Deserto', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Mesh Shopping Tote Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Crystal Slide Black [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Crystal Slide Black [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Brushed leather kitten thong sandal in Acqua [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Brushed leather kitten thong sandal in Alabastro [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Triangle Loafers Women Black Leather [41]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Triangle Logo Kitten Heels Black Leather [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Rubber Cage Platform Sandal Begonia [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Rubber Cage Platform Sandal Begonia [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2005 Nylon Multipochette Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Reedition 2005 Nylon Multipochette Acqua (Pastel Green)', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Duet Re-Nylon Shoulder Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('38', 'PRADA Cleo Vertical Small Tote Brushed Leather black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('39', 'SF Gancini Chunky Sneakers in White/Silver [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Espadriles Black [36.5] insole 22,5cm', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Espadriles Camel [36.5] insole 22,5cm', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Espadriles Camel [37.5] insole 23,5cm', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Lia Slides in Peach [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Flossy Crystal and Pearl Clutch with Black Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Butterfly Flossy Crystal and Pearl Clutch with Silver Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('40', 'SOPHIA WEBSTER Bibi Flatshoes in Champagne Glitter - Embroidered Rose Gold Butterfly Logo', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Tiny Falabella Tote Espresso GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Mini Falabella Fold Over Tote Bag in All Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Falabella Fold Over Tote Bag Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Falabella Small Tote Bag Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Falabella Mini Shoulder Bag Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('41', 'SMCC Falabella Tiny Tote Bag Butter Ceam GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Miller Cloud Sandals Black [6]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Miller Cloud Sandals Black [9]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Miller Cloud Sandals Black [10]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Tote Saffiano Black (Emerson Shopper)', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Tote Saffiano Sea Wind (Emerson Shopper)', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Tote Saffiano Almond (Emerson Shopper Cardamom)', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Tote Saffiano Grey Heron (Emerson Shopper)', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Emerson Phone Holder GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Canvas Espadrilles in Ivory Multi [6]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Canvas Espadrilles in Ivory Multi [7]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Canvas Espadrilles in Ivory Multi [8]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Emmy Pearl Tan Leather [7]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Thea Mini Sling Shoulder Bag -Tan', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Ivory [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Ivory [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Black [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Black [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Black [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Black [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Bubble Jelly Sandals - Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Blake Embossed Mini Camera Green Croco Bag', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Jelly Sandal Studded in Ivory [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Jelly Sandal Studded in Ivory [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Blue Walker Mini Canvas Top Handle Sling', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Perry Bombe Double Zip Crossbody Devond Sand', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Perry Bombe Double Zip Crossbody Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Eleanor Crossboy Bag in Moose', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Kira Chevron Convertible Shoulder Bag Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Mini Kira Chevron Convertible Shoulder Bag New Cream GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Canvas Tote Medley Stripe Multicolour', '14', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Minnie Snake Print cap toe Ballerina in Warm Roccia / Perfect Black [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Daisy Espadrille Sport Sandal in Black/Ivory [5.5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Miller Medium Shoulder Bag Celadon GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Fleming Soft Small Convertible Shoulder Bag Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Fleming Matte Small Convertible Shoulder Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Fleming Matte Medium Convertible Shoulder Bag Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Eleanor Convertible Medium Shoulder Bag Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Eleanor Clutch in Cream', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Eleanor Clutch in Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Willa Matte Small Shoulder Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Geo Logo Tote Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Geo Logo Tote Ivory', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Medium Ella Tote Navy', '14', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Belt Reversible Vlogo 2cm Black / Red [70]', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Belt Reversible Vlogo 2cm Black / Red [80]', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 70', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 75', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 80', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Signature WOC All Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO VLogo Shoulder and Belt Bag in Tan', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Leather WoC with Handle Light Blue', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO VLogo Compact Trifold Wallet Black', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO VLTN card holder', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Chunky 6cm in Nude Poudre [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Chunky 6cm in Nude Poudre [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Chunky 6cm in Nude Poudre [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Chunky 6cm in Nude Poudre [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Mule in Calfskin 6.5 [35,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Mule in Calfskin 6.5 [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Mule in Calfskin 6.5 [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Alcove Slingback Pump Black [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Alcove Sling Back Nude [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [38,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [41]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Kitten Mule 5cm Ivory Patent [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in Nude [34]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in White [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in White [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Heels 10cm in Nude Poudre Patent [38,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Heels 10cm in Nude Poudre Patent [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Flats Niagra [35,5] insole 23', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Flats Niagra [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Nude Poudre [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Nude Poudre [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Nude Poudre [39] insole 26', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Strappy Sandal Nude Poudre [40] insole 27', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ankle Strap Pumps Heels 10cm in All Black Calf [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ankle Strap Pumps Heels 10cm in All Black Calf [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flat Caged Nude Patent [36,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [37,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Rockstud Top Handle Black Grained', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Mini Hobo Rose Cannele Grained Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Men VLTN star Crossbody Black Nylon', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL WoC 22cm Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL WoC 19cm Camel GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown WoC Nude Grained Leather GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown WoC Croc-Stamped White Ivory GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Monogram Phone Holder Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Croc Stamp White GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Croc Stamp Black GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Croc Stamp Eros GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Nude Grained GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch White Grained GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Black Grained GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Bill pouch Large Tan GHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Paris Tribute Espradilles Wedges Heels Black [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute high heels 14cm in nude patent [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Low Heels 10cm in Tan Calf [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Low Heels 10cm in Tan Calf [35,5]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Low Heels 10cm in Tan Calf [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [37]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [38]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [40]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Kate Medium Beige Croco with Tassel GHW 24cm', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Kate Medium Shoulder Bag in Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Kate Black Calf Pump 8mm [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Kate WoC in Bordeaux GHW with Tassels', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Small Loulou in Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Medium Loulou in Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Small Loulou in All Black', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'Ysl Espadrilles Monogram Black [41]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Tiny Monogram Zippered Tablet Holder Black Ghw', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Monogram Envelope Plaque Clutch Black GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Envelope Small Shoulder Bag Matelasse Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Envelope WoC 22cm Mix Matelasse Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Envelope WoC 22cm Mix Matelasse Beige GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Envelope Clutch Vert Khaki Grained', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Medium Monogramme Niki Shoulder Bag in Grey Khaki', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('6', 'BV The Chain Pouch in Seagrass GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('36', 'MOSCHINO Women Logo Platform Pool Slides in Black [39]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Small Loulou in Taupe', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Loulou Puffer Mini Beige GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Loulou Puffer Small Black GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Pico Belt Bag Light Taupe', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('9', 'CELINE Pico Belt Bag Grey', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('15', 'DIOR Etoile Ring', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI FF Logo Bifold Wallet', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo Leather WoC with Handle Black', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO VLogo Double Strap Belt 3cm Black White Tan [75]', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('19', 'GIVENCHY Antigona Small Cloud Grey Smooth Leather', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('17', 'FENDI FF Logo WoC', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Mini Edge Blanc GHW', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Bumbag Logo Cross Regular Taupe', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Wallet Trifold Black GHW', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Robinson Card Case Black', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB Robinson Card Case Grey GHW', '16', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('42', 'TB All Black Thong [36]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('3', 'BALENCIAGA Small Graffiti Dark Grey', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO VLOGO Signature Earrings in Metal and Swarovski', '1', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Bumbag Regular Tiger Sand', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('27', 'KENZO Small Kenzogram Bucket Bag in Black with Shoulder Strap', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Expandable Travel Bag Cognac', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('31', 'MANOLO BLAHNIK Hangisi Pump 7cm in Black with Black Crystal [35]', '6', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('18', 'FURLA Lipari S Bucket Bag Beige', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('29', 'LC Le Pliage Paris Saint Tropez Bucket Bag Orange', '2', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Uptown Pouch Croc Stamp Black SHW', '11', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('44', 'YSL Kate Medium Shoulder Bag in Black with Tassel GHW', '4', null);
INSERT INTO `products` (brand_id,name,category_id,qty_onhand) VALUES ('43', 'VALENTINO Vlogo card holder', '16', null);
