/*
Navicat MySQL Data Transfer

Source Server         : Local Server
Source Server Version : 50733
Source Host           : localhost:3306
Source Database       : vl_online

Target Server Type    : MYSQL
Target Server Version : 50733
File Encoding         : 65001

Date: 2022-07-29 09:03:35
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `products`
-- ----------------------------
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_track_lot_number` tinyint(1) DEFAULT '0',
  `category_id` int(11) DEFAULT NULL,
  `brand_id` int(11) DEFAULT NULL,
  `product_cost` double(8,2) DEFAULT NULL,
  `product_price` double(8,2) DEFAULT NULL,
  `qty_onhand` int(11) DEFAULT '0',
  `qty_allocated` int(11) DEFAULT '0',
  `qty_received` int(11) DEFAULT '0',
  `qty_shipped` int(11) DEFAULT '0',
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `products_code_index` (`code`),
  KEY `products_name_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=589 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of products
-- ----------------------------
INSERT INTO `products` VALUES ('1', null, 'ALAIA Garance Phone Bag in Sable - Tan', '0', '4', '1', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('2', null, 'AMINA MUADDI Begum Pump Shadow Lollipop 9.5cm Crystal Buckle [37]', '0', '6', '2', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('3', null, 'AMINA MUADDI Begum Pump Shadow Lollipop 9.5cm Crystal Buckle [38]', '0', '6', '2', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('4', null, 'AMINA MUADDI Begum Pump Glass PVC Pink [36,5]', '0', '6', '2', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('5', null, 'AMINA MUADDI Begum Pump Glass PVC Pink [37]', '0', '6', '2', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('6', null, 'AMINA MUADDI Begum Pump Glass PVC Pink [38]', '0', '6', '2', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('7', null, 'AMINA MUADDI Begum Pump Glass PVC Pink [39]', '0', '6', '2', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('8', null, 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [36,5]', '0', '6', '2', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('9', null, 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [38,5]', '0', '6', '2', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('10', null, 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [38]', '0', '6', '2', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('11', null, 'AMINA MUADDI Begum Crystal Buckle Mules Heels Fairytale [39]', '0', '6', '2', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('12', null, 'BALENCIAGA Shopping Phone Holder Logo White Croco', '0', '4', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('13', null, 'BALENCIAGA Mini Giant Haussmanian Gris', '0', '2', '3', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('14', null, 'BALENCIAGA Mini Giant Black SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('15', null, 'BALENCIAGA Small Giant Black SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('16', null, 'BALENCIAGA Mini Edge Black GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('17', null, 'BALENCIAGA Small Edge Black GHW', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('18', null, 'BALENCIAGA Regular Edge Black GHW', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('19', null, 'BALENCIAGA Mini Edge Grey (Gris) SHW', '0', '2', '3', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('20', null, 'BALENCIAGA Mini Edge Grey (Gris) GHW', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('21', null, 'BALENCIAGA Small Edge Grey (Gris) GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('22', null, 'BALENCIAGA Small Edge Grey (Gris) SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('23', null, 'BALENCIAGA Regular Edge Grey (Gris) SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('24', null, 'BALENCIAGA Small Edge White Blanc SHW', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('25', null, 'BALENCIAGA Small Edge White Blanc GHW', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('26', null, 'BALENCIAGA Small Edge Mink SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('27', null, 'BALENCIAGA Regular Edge Shinny Rose Des Sables AJ SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('28', null, 'BALENCIAGA Small Classic Anthracite GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('29', null, 'BALENCIAGA Small Classic Anthracite SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('30', null, 'BALENCIAGA Small Classic Black Shinny AJ RHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('31', null, 'BALENCIAGA Small Classic Black Matte RHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('32', null, 'BALENCIAGA Small Classic Black SHW', '0', '2', '3', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('33', null, 'BALENCIAGA Mini Classic Black GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('34', null, 'BALENCIAGA Small Classic Black GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('35', null, 'BALENCIAGA Small Graffiti Black White RHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('36', null, 'BALENCIAGA Clip M clutch/pochette in Navy Blue', '0', '11', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('37', null, 'BALENCIAGA Ville XXS Dark Taupe', '0', '2', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('38', null, 'BALENCIAGA Neo Lift Bumbag Grey', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('39', null, 'BALENCIAGA BB Trifold Mini GHW Wallet', '0', '16', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('40', null, 'BALENCIAGA BB Women clutch in Croco Red Stamp', '0', '4', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('41', null, 'BALENCIAGA Cabas S Black Crinkle Leather', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('42', null, 'BALENCIAGA Cabas S Grey Crinkle Leather', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('43', null, 'BALENCIAGA Le Cagole XS Shoulder Crocodile Beige GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('44', null, 'BALENCIAGA Le Cagole XS Shoulder Crocodile Lilac GHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('45', null, 'BALENCIAGA Le Cagole XS Shoulder Crocodile Black', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('46', null, 'BALENCIAGA Le Cagole XS Shoulder Crocodile Pink', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('47', null, 'BALENCIAGA Le Cagole XS Shoulder Crocodile White SHW', '0', '2', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('48', null, 'BALENCIAGA Women Chunky Slide Sandals in Beige [35]', '0', '6', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('49', null, 'BALENCIAGA Women Chunky Slide Sandals in White [35]', '0', '6', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('50', null, 'BALENCIAGA Women Chunky Slide Sandals in White [36]', '0', '6', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('51', null, 'BALENCIAGA Track Rubber Sandal Pink/Black [38] insole 25cm', '0', '6', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('52', null, 'BALENCIAGA Track Rubber Sandal Pink/Black [39]', '0', '6', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('53', null, 'BALENCIAGA Track Rubber Sandal Beige [40] insole 27cm', '0', '6', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('54', null, 'BALENCIAGA Giant Card Case Rouge/Red', '0', '16', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('55', null, 'BALENCIAGA Giant Card Case Black GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('56', null, 'BALENCIAGA Giant Card Case Haussmanian GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('57', null, 'BALENCIAGA Classic Card Case Anthracite GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('58', null, 'BALENCIAGA Mini Neo Classic Trifold wallet black GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('59', null, 'BALENCIAGA Classic City Bifold Card', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('60', null, 'BALENCIAGA Long Zippy Wallet Metallic Edge in Black GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('61', null, 'BALENCIAGA Edge Mini Wallet Grey GHW', '0', '16', '3', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('62', null, 'BALENCIAGA Edge Mini Wallet Black GHW', '0', '16', '3', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('63', null, 'BALLY Asher Sneaker Black Leather [43]', '0', '6', '4', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('64', null, 'BALLY Elsa with logo 5.5cm Heels Black Calf [36]', '0', '6', '4', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('65', null, 'BALLY Elsa with logo 5.5cm Heels Black Calf [37]', '0', '6', '4', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('66', null, 'BALLY Elsa with logo 5.5cm Heels Black Calf [39]', '0', '6', '4', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('67', null, 'BALLY Women Mandye White Sneakers [36]', '0', '6', '4', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('68', null, 'BALLY Women Mandye White Sneakers [36.5]', '0', '6', '4', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('69', null, 'BALLY Women Mandye White Sneakers [37]', '0', '6', '4', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('70', null, 'BALLY Women Mandye White Sneakers [37.5]', '0', '6', '4', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('71', null, 'BAO BAO ISSEY MIYAKE Prism Tote Bag in Blush Lucent', '0', '14', '5', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('72', null, 'BV The Chain Pouch in Black SHW Butter Calf SHW', '0', '4', '6', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('73', null, 'BV Mini Jodie Caramel', '0', '2', '6', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('74', null, 'BV Mini Jodie Blaster Patent Leather', '0', '2', '6', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('75', null, 'BV Mini Jodie Blaster', '0', '2', '6', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('76', null, 'BV Mini Jodie in Thunder Grey', '0', '2', '6', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('77', null, 'BV Mini Jodie Black', '0', '2', '6', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('78', null, 'BV Mini Jodie in Chalk', '0', '2', '6', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('79', null, 'BV Mini Jodie in Fountain', '0', '2', '6', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('80', null, 'BV Mini Jodie in Raintree', '0', '2', '6', null, null, '4', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('81', null, 'BOYY BOBBY 18 T-Rex', '0', '2', '7', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('82', null, 'BOY BOBBY 18 Alll Black', '0', '2', '7', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('83', null, 'BOY BOBBY 18 Meringue', '0', '2', '7', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('84', null, 'BOY BOBBY 23 Gold Buckle Tote Bag', '0', '2', '7', null, null, '3', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('85', null, 'BURBERRY Lola Small Lambskin Camel Shoulder Bag', '0', '2', '8', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('86', null, 'BURBERRY Knitted Check Olympia Pouch Birch Brown', '0', '4', '8', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('87', null, 'BURBERRY Vintage Check Bucket Hat [S]', '0', '3', '8', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('88', null, 'BURBERRY Vintage Check Bucket Hat [M]', '0', '3', '8', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('89', null, 'BURBERRY Vintage Check Bucket Hat [L]', '0', '3', '8', null, null, '-1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('90', null, 'BURBERRY Reversible Check Bucket Hat Yellow/Brown [M]', '0', '3', '8', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('91', null, 'BURBERRY Vintage Check Bifold Wallet Archive Beige', '0', '16', '8', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('92', null, 'CELINE Bucket Hat in Vinyl Black [M]', '0', '3', '9', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('93', null, 'CELINE Bucket Cotton Hat in Black [L]', '0', '3', '9', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('94', null, 'CELINE Monogram Bucket Hat [S]', '0', '3', '9', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('95', null, 'CELINE Nano Belt Bag Taupe', '0', '2', '9', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('96', null, 'CELINE Nano Belt Bag Grey', '0', '2', '9', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('97', null, 'CELINE Mini Vertical Cabas in Natural / Tan', '0', '4', '9', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('98', null, 'CELINE Pico Belt Green Clay', '0', '2', '9', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('99', null, 'CELINE Small Strap Wallet Textured Leather in Peony Carmin', '0', '16', '9', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('100', null, 'CELINE Triomphe Canvas Small Drawstring Bag White', '0', '16', '9', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('101', null, 'CHANEL Ballerina Lambskin Flat Beige [36]', '0', '6', '10', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('102', null, 'CHANEL Classicc Small Black Lamb GHW', '0', '2', '10', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('103', null, 'CHANEL 19 C19 Small White GHW', '0', '2', '10', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('104', null, 'CHANEL Boy Medium in Black Caviar GHW Size 25 x 15 x 9 cm', '0', '2', '10', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('105', null, 'CHANEL Boy Medium in Black Caviar RHW Size 25 x 15 x 9 cm', '0', '2', '10', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('106', null, 'Chanel Gift Tote A La Plage', '0', '2', '10', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('107', null, 'CHANEL Classic WOC Beige Caviar GHW with new CC strap chip', '0', '2', '10', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('108', null, 'CHIARA FERRAGNI Eyelike Bucket Bag in Baby Pink', '0', '2', '11', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('109', null, 'LOUBOUTIN Kate 70mm patent black pump [36,5]', '0', '6', '12', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('110', null, 'LOUBOUTIN Kate 70mm patent black pump [37]', '0', '6', '12', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('111', null, 'LOUBOUTIN Kate 70mm patent black pump [37,5]', '0', '6', '12', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('112', null, 'LOUBOUTIN Kate Heels 85mm Black Leather Pump [36]', '0', '6', '12', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('113', null, 'LOUBOUTIN Kate Heels 85mm Black Leather Pump [39]', '0', '6', '12', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('114', null, 'LOUBOUTIN Wallet Red All Card', '0', '16', '12', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('115', null, 'LOUBOUTIN Spikes Slide white studed [41]', '0', '6', '12', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('116', null, 'LOUBOUTIN Spikes Slide in Khaki [44]', '0', '6', '12', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('117', null, 'LOUBOUTIN Black Pool Flat Neoprene [42] insole 27cm', '0', '6', '12', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('118', null, 'COACH Tabby Pillow Metallic Soft Gold', '0', '2', '13', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('119', null, 'COMME DES GARCONS Girl X Disney limited edition Tshirt Minnie Ribbon [M]', '0', '12', '14', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('120', null, 'COMME DES GARCONS Girl X Disney limited edition Tshirt Minnie Ribbon [L]', '0', '12', '14', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('121', null, 'DIOR Mizza Square Beige Multicolour 100% silk', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('122', null, 'DIOR CD Logo Belt Reversible Black-Navy 35mm GHW [80] 98cm', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('123', null, 'DIOR CD Logo Belt Reversible Black-Navy 35mm GHW [100] 116cm', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('124', null, 'CHRISTIAN DIOR Saddle Belt 2cm Oblique [80]', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('125', null, 'CHRISTIAN DIOR Saddle Belt 2cm Oblique [85]', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('126', null, 'DIOR Saddle Trifold Compact Wallet Corda GHW', '0', '16', '15', null, null, '-1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('127', null, 'DIOR Grey Oblique Leather Wallet', '0', '16', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('128', null, 'DIOR Saddle WoC Blue Oblique', '0', '4', '15', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('129', null, 'DIOR Saddle WoC Black', '0', '4', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('130', null, 'CHRISTIAN DIOR Earring Tribales Pendant', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('131', null, 'DIOR J\'adior Earrings Tribales', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('132', null, 'DIOR J\'adior Pearl Tribales Earring', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('133', null, 'DIOR Logo Gold Earring', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('134', null, 'DIOR D Lune Necklace in Gold Metal with Star and Love', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('135', null, 'DIOR D Lune Heart and Star Earring', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('136', null, 'CHRISTIAN DIOR J\'adior Star Earrings', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('137', null, 'CHRISTIAN DIOR J\'adior Gold Graphic Metal with Resin', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('138', null, 'CHRISTIAN DIOR J\'adior Chain Bracelet Antique Gold with Pearls', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('139', null, 'CHRISTIAN DIOR J\'adior Bracelet Logo Gold', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('140', null, 'CHRISTIAN DIOR Wander Blue Oblique [36]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('141', null, 'CHRISTIAN DIOR Earring Petit Gold-Finish Metal', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('142', null, 'DIOR Granville Espadrille Toile De Jouy Grey [36]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('143', null, 'DIOR Granville Espadrille Toile De Jouy Grey [38]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('144', null, 'DIOR Deep Blue Toile De Jouy Rubber Sole (3cm) [36]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('145', null, 'DIOR Deep Blue Toile De Jouy Rubber Sole (3cm) [39]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('146', null, 'CHRISTIAN DIOR Granville Strippes Espadrilles Deep Blue [37]', '0', '6', '15', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('147', null, 'CHRISTIAN DIOR Toile De Jouy Scarf Grey size 90 x 90cm', '0', '1', '15', null, null, '3', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('148', null, 'CHRISTIAN DIOR Scarf/Shawl Silk Reversible in grey blue Oblique', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('149', null, 'DIOR Twilly Toile De Jouy in Grey', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('150', null, 'DIOR Twilly Logo Blue Stripes', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('151', null, 'DIOR Club M1U Sunglasses Oblique Navy', '0', '7', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('152', null, 'DIOR Friendship Textile Bracelet Red / Black', '0', '1', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('153', null, 'DIOR Friendship Textile Bracelet Rose Des Vents', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('154', null, 'DIOR Friendship Textile Bracelet Navy Oblique', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('155', null, 'DIOR Friendship Bracelet Black Lime Embroidery', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('156', null, 'DIOR Friendship Bracelet Green Pink Embroidery', '0', '1', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('157', null, 'DIOR Oblique Phone Holder', '0', '4', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('158', null, 'DIOR Dway Slide Embroidered Sandal Gold-Tone Metallic [37]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('159', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [35,5]', '0', '6', '15', null, null, '4', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('160', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [38,5]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('161', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [39]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('162', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [39,5]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('163', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [40]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('164', null, 'DIOR Dway Slide Embroidered Sandal in Navy Deep Blue [40,5]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('165', null, 'DIOR 30 Montaigne Sunglasses Square White GHW - Beige Lense', '0', '7', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('166', null, 'CHRISTIAN DIOR Dway Slides Black Embroidered Cotton and Shearling [39]', '0', '6', '15', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('167', null, 'DIOR Revolution Slide Oblique Navy [35]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('168', null, 'DIOR Revolution Slide Oblique Navy [36]', '0', '6', '15', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('169', null, 'FLP WoC Empire Green', '0', '4', '16', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('170', null, 'FENDI Logo WoC Grey', '0', '4', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('171', null, 'FENDI Pomodorino Mini Bag Brown', '0', '2', '17', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('172', null, 'FENDI Colibri Slingback Pump Velvet Mesh Heels 5cm Beige [37,5]', '0', '6', '17', null, null, '3', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('173', null, 'Fendi FF cotton Baseball Cap Military Green with Yellow Line Unisex', '0', '3', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('174', null, 'FENDI Bucket Hat FF Logo Jacquard Brown Leather [M]', '0', '3', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('175', null, 'FENDI BTW Small Equator Multicolor', '0', '2', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('176', null, 'FENDI BTW Small Black', '0', '2', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('177', null, 'FENDI BTW Mini Camelia', '0', '2', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('178', null, 'FENDI Tour Le Jour ( Preloved)', '0', '2', '17', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('179', null, 'FENDI Continental Black Nappa Leather WoC GHW', '0', '4', '17', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('180', null, 'FURLA Bucket Costanza Nero', '0', '2', '18', null, null, '1', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('181', null, 'FURLA Mini Crossbody Bag Sand', '0', '2', '18', null, null, '3', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('182', null, 'GIVENCHY Antigona Mini Black Smooth Leather', '0', '2', '19', null, null, '2', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('183', null, 'GIVENCHY Antigona Small Grained Beige/Dune', '0', '2', '19', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('184', null, 'GIVENCHY Men Urban Street Sneakers in White [44]', '0', '6', '19', null, null, '0', '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('185', null, 'Goyard ST Louis PM Special Color Green', '0', '2', '20', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('186', null, 'Goyard ST Louis PM Special Color Grey', '0', '2', '20', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('187', null, 'Goyard ST Louis PM Special Color Black', '0', '2', '20', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('188', null, 'Goyard ST Louis PM Special Color Black Tan', '0', '2', '20', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('189', null, 'GUCCI Marmont Mini Backpack Round White Leather', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('190', null, 'GUCCI Marmont Mini Backpack Round Black Leather', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('191', null, 'GUCCI Marmont Mini Backpack Round Nude Leather', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('192', null, 'GUCCI GG Marmont Mini Shoulder Bag Black SHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('193', null, 'GUCCI GG Marmont Mini Shoulder Bag White SHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('194', null, 'GUCCI GG Marmont Small Flap Nude SHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('195', null, 'GUCCI GG Marmont Small Flap Nude GHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('196', null, 'GUCCI GG Marmont Small Camera Bag Porcelain Rose GHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('197', null, 'GUCCI Enamel GG Marmont Small Camera Bag Emerald Blue GHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('198', null, 'GUCCI Enamel GG Marmont Small Camera Bag Emerald White GHW', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('199', null, 'GUCCI GG Marmont Large Pouch In Gold Tone Tan', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('200', null, 'GUCCI Mini Padlock Top Handle Beige Ebony Black', '0', '4', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('201', null, 'GUCCI Horsebit 1955 Mini /phone holder in Ivory', '0', '4', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('202', null, 'GUCCI Guccissima Dome Mini Top Handle Beige', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('203', null, 'GUCCI Guccissima Dome Mini Top Handle Grey', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('204', null, 'GUCCI Ophidia Dome Halfmoon Flower Flora / Floral', '0', '2', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('205', null, 'GUCCI Ophidia Small Flora with Chain shoulder Bag', '0', '4', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('206', null, 'GUCCI Rubber Dad Sandal White [39]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('207', null, 'GUCCI Rubber Dad Sandal White [40]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('208', null, 'GUCCI Rubber Platform Black (Runs Big) [35] insole 23', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('209', null, 'GUCCI Rubber Platform Black (Runs Big) [40] insole 28', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('210', null, 'GUCCI Rubber Platform White (Runs Big) [35] insole 23', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('211', null, 'GUCCI Women GG Espadrilles Mules in Black GHW [36,5]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('212', null, 'GUCCI Women GG Espadrilles Mules in Black GHW [37]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('213', null, 'GUCCI Women GG Espadrilles Mules in White GHW [35,5]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('214', null, 'GUCCI Women GG Canvas Linen Espadrille White Multicolor [39]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('215', null, 'GUCCI Women GG Double Sole Espadrilles in white GHW [39]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('216', null, 'GUCCI GG Supreme Canvas Ankle Boot Leather White Beige', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('217', null, 'GUCCI Princetown Horsebit Mules Beige [35]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('218', null, 'GUCCI Princetown Horsebit Mules Beige [36]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('219', null, 'GUCCI Princetown Horsebit Mules Beige [36,5]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('220', null, 'GUCCI Princetown GG Flora Mules [37]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('221', null, 'GUCCI GG Linen Espadrilles Multicolour', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('222', null, 'GUCCI Marmont Platform Sandal Black Leather GHW [37]', '0', '6', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('223', null, 'GUCCI GG Intarsia-Knit Cardigan Beige [S]', '0', '9', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('224', null, 'GUCCI GG Intarsia-Knit Cardigan Beige [M]', '0', '9', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('225', null, 'GUCCI GG Intarsia-Knit Cardigan [S]', '0', '9', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('226', null, 'GUCCI GG Intarsia-Knit Cardigan [M]', '0', '9', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('227', null, 'GUCCI GG Knit Cardigan Navy', '0', '9', '21', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('228', null, 'HERMES Sandal Egerie Jelly Vert Embrun [39]', '0', '6', '22', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('229', null, 'HERMES Oran Calfskin Sandal Gold [39]', '0', '6', '22', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('230', null, 'HERMES Oran Calfskin Sandal Gold [40]', '0', '6', '22', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('231', null, 'HERMES Eze Gold [38]', '0', '6', '22', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('232', null, 'BOSS Small Logo Jogger Pants in Black [M]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('233', null, 'BOSS Small Logo Jogger Pants in Black [L]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('234', null, 'BOSS Small Logo Jogger Pants in Black [XL]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('235', null, 'BOSS Small Logo Jogger Pants in Grey [M]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('236', null, 'BOSS Small Logo Jogger Pants in Grey [L]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('237', null, 'BOSS Small Logo Jogger Pants in Grey [XL]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('238', null, 'BOSS Logo Short Pants with Pocket Black [M]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('239', null, 'BOSS Logo Short Pants with Pocket Black [L]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('240', null, 'BOSS Polo Curved Black Gold [L]', '0', '10', '23', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('241', null, 'JACQUEMUS Le Grande Bambino in Black', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('242', null, 'JACQUEMUS Mini Le Chiquito Calfskin White', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('243', null, 'JACQUEMUS Mini Le Chiquito Black', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('244', null, 'JACQUEMUS Moyen Chiquito in Honey/Beige', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('245', null, 'JACQUEMUS Le Grand Chiquito White', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('246', null, 'JACQUEMUS Moyen Noeud Chiquito White Leather', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('247', null, 'JACQUEMUS Le Chiquito Long in White', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('248', null, 'JACQUEMUS Le Chiquito Long in Black', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('249', null, 'JACQUEMUS Le Chiquito Moten wicker tote in Tan', '0', '2', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('250', null, 'JACQUEMUS Le Bob Gadjo Bucket Hat in off white [56]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('251', null, 'JACQUEMUS Le Bob Gadjo Bucket Hat in off white [58]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('252', null, 'JACQUEMUS Le Bob Gadjo Bucket Hat in khaki [58]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('253', null, 'JACQUEMUS Le Bob Gadjo Bucket Hat in black [56]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('254', null, 'JACQUEMUS Le Bob Gadjo Bucket Hat in black [58]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('255', null, 'JACQUEMUS Le Bob Artichaut Bucket Cap Wide Brimmed Black [56]', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('256', null, 'JACQUEMUS Le Chapeau Rattan Beach Hat', '0', '3', '24', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('257', null, 'JIMMY CHOO Saeda 10cm Slingback Pumps Heels in Glitter Crystal Chain [37]', '0', '6', '25', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('258', null, 'JIMMY CHOO Saeda 10cm Slingback Pumps Heels in Glitter Crystal Chain [39]', '0', '6', '25', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('259', null, 'JIMMY CHOO Saeda Slingback Pumps in Gold Metallic Crystal Chain (10cm) [38]', '0', '6', '25', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('260', null, 'JIMMY CHOO Slingback Flat in Black [38,5]', '0', '6', '25', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('261', null, 'KARL New Icon Neon Logo Top Handle with Removable Strap', '0', '2', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('262', null, 'KARL Rhinestone Tee Black [M]', '0', '15', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('263', null, 'KARL Rhinestone Tee Black [L]', '0', '15', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('264', null, 'KARL Rhinestone Tee White [M]', '0', '15', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('265', null, 'KARL Rhinestone Tee White [L]', '0', '15', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('266', null, 'KARL Rhinestone Jacket Soft White [M]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('267', null, 'KARL New Icon Neo Bumbag', '0', '2', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('268', null, 'KARL Hoodie Jacket Stripe Rose [M]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('269', null, 'KARL Hoodie Jacket Stripe Marine [M]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('270', null, 'KARL Hoodie Jacket Stripe Marine [L]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('271', null, 'KARL Hoodie Jacket Stripe Black [M]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('272', null, 'KARL Hoodie Jacket Stripe Black [L]', '0', '8', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('273', null, 'KARL Long Sleeve Black [S]', '0', '12', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('274', null, 'KARL Long Sleeve White [XS]', '0', '12', '26', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('275', null, 'KENZO Sport Little X TShirt Dress Purple [S]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('276', null, 'KENZO Sport Little X TShirt Dress Purple [M]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('277', null, 'KENZO Sport Little X TShirt Dress Purple [XL]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('278', null, 'KENZO Black and White Monogram Cap', '0', '3', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('279', null, 'KENZO Tiger Canvas Bebeboo Mini Backpack in Black Brown / Gold', '0', '2', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('280', null, 'KENZO Bumbag Logo Cross Regular Black', '0', '2', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('281', null, 'KENZO Clutch Cross Logo Black', '0', '4', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('282', null, 'KENZO K Logo Clutch Mint Colour', '0', '4', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('283', null, 'KENZO Kampus Tiger Clutch Large in Black Leather', '0', '4', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('284', null, 'KENZO Tiger Crest Trainer Men [42]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('285', null, 'KENZO Tiger Campus Card Holder with Leather Strap', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('286', null, 'KENZO Tiger Crest Trainer Men [43]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('287', null, 'KENZO Tali Phone Holder in Black Leather with Removable Chain Strap', '0', '4', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('288', null, 'KENZO Women Tiger Espadrilles in Navy blue/Red Canvas [40]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('289', null, 'KENZO K-Skate Tiger Slip On Sneakers Blush / Poudre [37]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('290', null, 'KENZO K-Skate Tiger Slip On Sneakers Blush / Poudre [38]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('291', null, 'KENZO Jaquard Monogram Knitted Dress Deep Orange [XS]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('292', null, 'KENZO Jaquard Monogram Knitted Dress Deep Orange [S]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('293', null, 'KENZO Jaquard Monogram Knitted Dress Deep Orange [M]', '0', '5', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('294', null, 'KENZO Reversible Monogram/ White Bucket Hat [M]', '0', '3', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('295', null, 'KENZO Women Tiger Espadrilles in Black [37]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('296', null, 'KENZO Women Tiger Espadrilles in Black [38]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('297', null, 'KENZO Women Tiger Espadrilles in Black [39]', '0', '6', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('298', null, 'LOEWE Small Rattan Basket Bag in Natural Tan Brown', '0', '2', '28', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('299', null, 'LOEWE Small Rattan Basket Bag in Natural White', '0', '2', '28', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('300', null, 'LOEWE Small Rattan Basket Bag in Natural Tan Navy', '0', '2', '28', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('301', null, 'LC Le Pliage Small Long Handle Navy', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('302', null, 'LC Le Pliage Cuir Small Dessert', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('303', null, 'LC Le Pliage Cuir Small Beige', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('304', null, 'LC Le Pliage Cuir Small Beige Ivory', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('305', null, 'LC Le Pliage Cuir Mini Dessert', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('306', null, 'LC Le Pliage Cuir Small Bag Turtledove Metis', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('307', null, 'LC Le Pliage Cuir Mini Turtledove', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('308', null, 'LC Le Pliage Cuir Mini Sienna', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('309', null, 'LC Le Pliage Paris Saint Tropez Bucket Bag Brown', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('310', null, 'LC Le Pliage Paris Saint Tropez Bucket Bag Black', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('311', null, 'LC Le Pliage Paris Saint Tropez Bucket Bag Green', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('312', null, 'LC Le Pliage Paris Saint Tropez Bucket Bag Maroon', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('313', null, 'LC Le Pliage Filet White', '0', '14', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('314', null, 'LC Le Pliage Filet Black', '0', '14', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('315', null, 'LC Le Pliage Filet Top Handle Bag Navy', '0', '14', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('316', null, 'LC Le Pliage Mini Filet Sling Yellow', '0', '4', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('317', null, 'LC Le Pliage Mini Filet Sling Blush', '0', '4', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('318', null, 'LC Le Pliage Mini Filet Sling Black', '0', '4', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('319', null, 'LC Le Pliage Mini Filet Sling Ecru', '0', '4', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('320', null, 'LC Le Pliage Neo Mini Très Paris Navy', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('321', null, 'LC Le Pliage Small City Black', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('322', null, 'LC Le Pliage Long zip around Wallet Black White Leather', '0', '16', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('323', null, 'LC Roseau Small Powder Crossbody Bag Leather', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('324', null, 'LC Essential Toile Tote Ecru', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('325', null, 'LC Le Pliage Bagpack in Cognac', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('326', null, 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [37]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('327', null, 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [38,5]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('328', null, 'MALONE SOULIERS Maureen Flat Mules Leather Black Gold [38,5]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('329', null, 'MALONE SOULIERS Maureen Pump 70mm Black nude [37]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('330', null, 'MALONE SOULIERS Maureen Pump 70mm Black nude [37,5]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('331', null, 'MALONE SOULIERS Maureen Pump 70mm Black nude [38]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('332', null, 'MALONE SOULIERS Maureen Flat /Mules Nude Blush [36,5]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('333', null, 'MALONE SOULIERS Maureen Flat /Mules Nude Blush [37,5]', '0', '6', '30', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('334', null, 'MANOLO BLAHNIK Hangisi 7cm mnude satin [36]', '0', '6', '31', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('335', null, 'MANOLO BLAHNIK Hangisi 7cm mnude satin [36,5]', '0', '6', '31', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('336', null, 'MANOLO BLAHNIK Hangisi heels 5cm in Royal Blue [38]', '0', '6', '31', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('337', null, 'MANOLO BLAHNIK Hangisi Pump 7cm in Black Glittered with White Crystal [35.5]', '0', '6', '31', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('338', null, 'MARC JACOBS Double Take Bag Black GHW', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('339', null, 'MARC JACOBS Snapshoot Top zip wallet Multicolour', '0', '16', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('340', null, 'MARC JACOBS Colorblock Compact Zip Leather Wallet', '0', '16', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('341', null, 'MARC JACOBS Snapshot Mini Wallet with Pocket Dusty Ruby Multi', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('342', null, 'MARC JACOBS Small Snapshot DTM Camera Bag All Black', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('343', null, 'MARC JACOBS Small Snapshot DTM Camera Bag Ink Grey', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('344', null, 'MARC JACOBS The Snapshot DTM Camera Bag White', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('345', null, 'MARC JACOBS The Snapshot WOC in Black/Red Multicolors', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('346', null, 'MARC JACOBS The Bold Open Wallet Black Leather', '0', '16', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('347', null, 'MARC JACOBS Wallet Grained Leather Smoke Almond', '0', '16', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('348', null, 'Peanuts X Marc Jacobs The Snoopy Mini Tote Bag Green Multi', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('349', null, 'MARC JACOBS The Hot Shot DTM All Black', '0', '4', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('350', null, 'MARC JACOBS Traveler Small Beige Canvas', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('351', null, 'MARC JACOBS Traveler Large Beige Canvas', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('352', null, 'MARC JACOBS Traveler Large Black Canvas', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('353', null, 'MARC JACOBS Traveler Large Blue Shadow Canvas', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('354', null, 'MARC JACOBS Traveler Large Slate Green Canvas', '0', '2', '32', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('355', null, 'MCM Mini Essential Crossbody Bag in Cognac', '0', '2', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('356', null, 'MCM Millie Flap Crossbody in Visetos', '0', '2', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('357', null, 'MCM Visetos Cognac Phone Holder with 6 card slot and zip', '0', '4', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('358', null, 'MCM Small Crossbody Pouch Trio Visetos Original Multi pochette Black/White/Cognac', '0', '4', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('359', null, 'MCM Klara Multifunction Phone Wallet Monogram Beige Leather', '0', '4', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('360', null, 'MCM Klara Multifunction Phone Wallet Monogram Black Leather', '0', '4', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('361', null, 'MCM Liz Shopper Reversible Medium Cognac', '0', '2', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('362', null, 'MCM Liz Shopper Reversible Medium Black', '0', '2', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('363', null, 'MCM Liz Shopper Reversible Medium White', '0', '2', '33', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('364', null, 'MIU MIU Matelasse Shoulder Bag in Black GHW (with 2 strap)', '0', '2', '34', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('365', null, 'MLB Front & Back Overfit New York Sweatshirt Black / Pink [XS]', '0', '13', '35', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('366', null, 'MLB Front & Back Overfit New York Sweatshirt Black / Pink [S]', '0', '13', '35', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('367', null, 'MLB Hobo Tote Bag Black', '0', '2', '35', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('368', null, 'MOSCHINO Sandal Slide White Black Embossed [36]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('369', null, 'MOSCHINO Logo Platform Sandal Black [39]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('370', null, 'MOSCHINO Logo Teddy Paint Tshirt White Woman White [XS]', '0', '15', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('371', null, 'MOSCHINO Logo Ribbon and Leather in Black [35]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('372', null, 'MOSCHINO Logo Ribbon and Leather in Black [36]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('373', null, 'MOSCHINO Logo Ribbon and Leather in Black [37]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('374', null, 'MOSCHINO Logo Ribbon and Leather in Black [38]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('375', null, 'MOSCHINO Logo Ribbon and Leather in Black [39]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('376', null, 'MOSCHINO Logo Ribbon and Leather in Black [40]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('377', null, 'PHILIP LIM Mini Odita Lattice Bag Leather Nude/White include Pouch', '0', '2', '37', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('378', null, 'PRADA Gabardine Crystal Embellished Slingback Pump [37]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('379', null, 'PRADA Gabardine Crystal Embellished Slingback Pump [38]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('380', null, 'PRADA Gabardine Crystal Embellished Slingback Pump [39]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('381', null, 'PRADA Plexi Heel 7.5cm Silver [39]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('382', null, 'PRADA Reedition nylon vella shoulder bag Black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('383', null, 'PRADA Reedition nylon vella shoulder bag Deserto', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('384', null, 'PRADA Reedition 2000 Tote Shoulder Bag Black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('385', null, 'PRADA Reedition 2000 Tote Shoulder Bag Glicine', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('386', null, 'PRADA Reedition 2005 in Black Saffiano', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('387', null, 'PRADA Reedition 2005 in Glicine', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('388', null, 'PRADA Reedition 2005 in Deserto', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('389', null, 'PRADA Mesh Shopping Tote Black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('390', null, 'PRADA Crystal Slide Black [35]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('391', null, 'PRADA Crystal Slide Black [36]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('392', null, 'PRADA Brushed leather kitten thong sandal in Acqua [36]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('393', null, 'PRADA Brushed leather kitten thong sandal in Alabastro [36]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('394', null, 'PRADA Triangle Loafers Women Black Leather [41]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('395', null, 'PRADA Triangle Logo Kitten Heels Black Leather [35]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('396', null, 'PRADA Rubber Cage Platform Sandal Begonia [38]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('397', null, 'PRADA Rubber Cage Platform Sandal Begonia [39]', '0', '6', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('398', null, 'PRADA Reedition 2005 Nylon Multipochette Black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('399', null, 'PRADA Reedition 2005 Nylon Multipochette Acqua (Pastel Green)', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('400', null, 'PRADA Duet Re-Nylon Shoulder Bag Black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('401', null, 'PRADA Cleo Vertical Small Tote Brushed Leather black', '0', '2', '38', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('402', null, 'SF Gancini Chunky Sneakers in White/Silver [37]', '0', '6', '39', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('403', null, 'SOPHIA WEBSTER Butterfly Espadriles Black [36.5] insole 22,5cm', '0', '6', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('404', null, 'SOPHIA WEBSTER Butterfly Espadriles Camel [36.5] insole 22,5cm', '0', '6', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('405', null, 'SOPHIA WEBSTER Butterfly Espadriles Camel [37.5] insole 23,5cm', '0', '6', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('406', null, 'SOPHIA WEBSTER Butterfly Lia Slides in Peach [37]', '0', '6', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('407', null, 'SOPHIA WEBSTER Butterfly Flossy Crystal and Pearl Clutch with Black Leather', '0', '2', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('408', null, 'SOPHIA WEBSTER Butterfly Flossy Crystal and Pearl Clutch with Silver Leather', '0', '2', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('409', null, 'SOPHIA WEBSTER Bibi Flatshoes in Champagne Glitter - Embroidered Rose Gold Butterfly Logo', '0', '2', '40', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('410', null, 'SMCC Tiny Falabella Tote Espresso GHW', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('411', null, 'SMCC Mini Falabella Fold Over Tote Bag in All Black', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('412', null, 'SMCC Falabella Fold Over Tote Bag Black GHW', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('413', null, 'SMCC Falabella Small Tote Bag Black GHW', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('414', null, 'SMCC Falabella Mini Shoulder Bag Black GHW', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('415', null, 'SMCC Falabella Tiny Tote Bag Butter Ceam GHW', '0', '2', '41', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('416', null, 'TB Miller Cloud Sandals Black [6]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('417', null, 'TB Miller Cloud Sandals Black [9]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('418', null, 'TB Miller Cloud Sandals Black [10]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('419', null, 'TB Mini Tote Saffiano Black (Emerson Shopper)', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('420', null, 'TB Mini Tote Saffiano Sea Wind (Emerson Shopper)', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('421', null, 'TB Mini Tote Saffiano Almond (Emerson Shopper Cardamom)', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('422', null, 'TB Mini Tote Saffiano Grey Heron (Emerson Shopper)', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('423', null, 'TB Emerson Phone Holder GHW', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('424', null, 'TB Canvas Espadrilles in Ivory Multi [6]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('425', null, 'TB Canvas Espadrilles in Ivory Multi [7]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('426', null, 'TB Canvas Espadrilles in Ivory Multi [8]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('427', null, 'TB Emmy Pearl Tan Leather [7]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('428', null, 'TB Thea Mini Sling Shoulder Bag -Tan', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('429', null, 'TB Bubble Jelly Sandals - Ivory [38]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('430', null, 'TB Bubble Jelly Sandals - Ivory [39]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('431', null, 'TB Bubble Jelly Sandals - Black [35]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('432', null, 'TB Bubble Jelly Sandals - Black [36]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('433', null, 'TB Bubble Jelly Sandals - Black [37]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('434', null, 'TB Bubble Jelly Sandals - Black [38]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('435', null, 'TB Bubble Jelly Sandals - Black [39]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('436', null, 'TB Blake Embossed Mini Camera Green Croco Bag', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('437', null, 'TB Jelly Sandal Studded in Ivory [36]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('438', null, 'TB Jelly Sandal Studded in Ivory [39]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('439', null, 'TB Blue Walker Mini Canvas Top Handle Sling', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('440', null, 'TB Perry Bombe Double Zip Crossbody Devond Sand', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('441', null, 'TB Perry Bombe Double Zip Crossbody Black', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('442', null, 'TB Eleanor Crossboy Bag in Moose', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('443', null, 'TB Mini Kira Chevron Convertible Shoulder Bag Black GHW', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('444', null, 'TB Mini Kira Chevron Convertible Shoulder Bag New Cream GHW', '0', '4', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('445', null, 'TB Canvas Tote Medley Stripe Multicolour', '0', '14', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('446', null, 'TB Minnie Snake Print cap toe Ballerina in Warm Roccia / Perfect Black [38]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('447', null, 'TB Daisy Espadrille Sport Sandal in Black/Ivory [5.5]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('448', null, 'TB Miller Medium Shoulder Bag Celadon GHW', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('449', null, 'TB Fleming Soft Small Convertible Shoulder Bag Black GHW', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('450', null, 'TB Fleming Matte Small Convertible Shoulder Bag Black', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('451', null, 'TB Fleming Matte Medium Convertible Shoulder Bag Black', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('452', null, 'TB Eleanor Convertible Medium Shoulder Bag Black GHW', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('453', null, 'TB Eleanor Clutch in Cream', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('454', null, 'TB Eleanor Clutch in Black', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('455', null, 'TB Willa Matte Small Shoulder Black', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('456', null, 'TB Geo Logo Tote Black', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('457', null, 'TB Geo Logo Tote Ivory', '0', '2', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('458', null, 'TB Medium Ella Tote Navy', '0', '14', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('459', null, 'VALENTINO Belt Reversible Vlogo 2cm Black / Red [70]', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('460', null, 'VALENTINO Belt Reversible Vlogo 2cm Black / Red [80]', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('461', null, 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 70', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('462', null, 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 75', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('463', null, 'VALENTINO Vlogo Reversible Signature Belt Niagara GHW 80', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('464', null, 'VALENTINO Vlogo Signature WOC All Black', '0', '4', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('465', null, 'VALENTINO VLogo Shoulder and Belt Bag in Tan', '0', '4', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('466', null, 'VALENTINO Vlogo Leather WoC with Handle Light Blue', '0', '4', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('467', null, 'VALENTINO VLogo Compact Trifold Wallet Black', '0', '16', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('468', null, 'VALENTINO VLTN card holder', '0', '16', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('469', null, 'VALENTINO Chunky 6cm in Nude Poudre [36,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('470', null, 'VALENTINO Chunky 6cm in Nude Poudre [36]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('471', null, 'VALENTINO Chunky 6cm in Nude Poudre [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('472', null, 'VALENTINO Chunky 6cm in Nude Poudre [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('473', null, 'VALENTINO Roman Stud Mule in Calfskin 6.5 [35,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('474', null, 'VALENTINO Roman Stud Mule in Calfskin 6.5 [36]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('475', null, 'VALENTINO Roman Stud Mule in Calfskin 6.5 [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('476', null, 'VALENTINO Rockstud Alcove Slingback Pump Black [35]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('477', null, 'VALENTINO Rockstud Alcove Sling Back Nude [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('478', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('479', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [37,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('480', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('481', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [38,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('482', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [39]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('483', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [40]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('484', null, 'VALENTINO Rockstud Mules Slipper Flat in Nude Poudre Patent [41]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('485', null, 'VALENTINO Rockstud Kitten Mule 5cm Ivory Patent [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('486', null, 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in Nude [34]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('487', null, 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in White [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('488', null, 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [36]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('489', null, 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('490', null, 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('491', null, 'Valentino Rockstud Wedges Heels Sandal 9.5cm in Black [39]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('492', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [35]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('493', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [36]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('494', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('495', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [37,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('496', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('497', null, 'VALENTINO Roman Stud Slide Sandal in Quilted Neppa Rose Canelle [39]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('498', null, 'VALENTINO Rockstud Wedges Heels Sandal 9.5cm in White [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('499', null, 'VALENTINO Rockstud Heels 10cm in Nude Poudre Patent [38,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('500', null, 'VALENTINO Rockstud Heels 10cm in Nude Poudre Patent [40]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('501', null, 'VALENTINO Rockstud Strappy Sandal Flats Niagra [35,5] insole 23', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('502', null, 'VALENTINO Rockstud Strappy Sandal Flats Niagra [37,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('503', null, 'VALENTINO Rockstud Strappy Sandal Nude Poudre [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('504', null, 'VALENTINO Rockstud Strappy Sandal Nude Poudre [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('505', null, 'VALENTINO Rockstud Strappy Sandal Nude Poudre [39] insole 26', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('506', null, 'VALENTINO Rockstud Strappy Sandal Nude Poudre [40] insole 27', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('507', null, 'VALENTINO Rockstud Ankle Strap Pumps Heels 10cm in All Black Calf [36]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('508', null, 'VALENTINO Rockstud Ankle Strap Pumps Heels 10cm in All Black Calf [37,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('509', null, 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [35]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('510', null, 'VALENTINO Rockstud Ballerina/Flat Caged Nude Patent [36,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('511', null, 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('512', null, 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('513', null, 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [39]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('514', null, 'VALENTINO Rockstud Ballerina/Flats in nude Patent leather [40]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('515', null, 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [37]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('516', null, 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [37,5]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('517', null, 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [38]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('518', null, 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [39]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('519', null, 'VALENTINO Rockstud Ballerina/Flats in nude Grain leather [40]', '0', '6', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('520', null, 'VALENTINO Rockstud Top Handle Black Grained', '0', '2', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('521', null, 'VALENTINO Mini Hobo Rose Cannele Grained Leather', '0', '2', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('522', null, 'VALENTINO Men VLTN star Crossbody Black Nylon', '0', '2', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('523', null, 'YSL WoC 22cm Black GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('524', null, 'YSL WoC 19cm Camel GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('525', null, 'YSL Uptown WoC Nude Grained Leather GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('526', null, 'YSL Uptown WoC Croc-Stamped White Ivory GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('527', null, 'YSL Monogram Phone Holder Black GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('528', null, 'YSL Uptown Pouch Croc Stamp White GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('529', null, 'YSL Uptown Pouch Croc Stamp Black GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('530', null, 'YSL Uptown Pouch Croc Stamp Eros GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('531', null, 'YSL Uptown Pouch Nude Grained GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('532', null, 'YSL Uptown Pouch White Grained GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('533', null, 'YSL Uptown Pouch Black Grained GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('534', null, 'YSL Bill pouch Large Tan GHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('535', null, 'YSL Paris Tribute Espradilles Wedges Heels Black [35]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('536', null, 'YSL Tribute high heels 14cm in nude patent [38]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('537', null, 'YSL Tribute Low Heels 10cm in Tan Calf [35]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('538', null, 'YSL Tribute Low Heels 10cm in Tan Calf [35,5]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('539', null, 'YSL Tribute Low Heels 10cm in Tan Calf [40]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('540', null, 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [37]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('541', null, 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [38]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('542', null, 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [39]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('543', null, 'YSL Tribute Wedges Espadrilles 12cm Brown Tan Ambra [40]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('544', null, 'YSL Kate Medium Beige Croco with Tassel GHW 24cm', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('545', null, 'YSL Kate Medium Shoulder Bag in Black GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('546', null, 'YSL Kate Black Calf Pump 8mm [36]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('547', null, 'YSL Kate WoC in Bordeaux GHW with Tassels', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('548', null, 'YSL Small Loulou in Black GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('549', null, 'YSL Medium Loulou in Black GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('550', null, 'YSL Small Loulou in All Black', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('551', null, 'Ysl Espadrilles Monogram Black [41]', '0', '6', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('552', null, 'YSL Tiny Monogram Zippered Tablet Holder Black Ghw', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('553', null, 'YSL Monogram Envelope Plaque Clutch Black GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('554', null, 'YSL Envelope Small Shoulder Bag Matelasse Black GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('555', null, 'YSL Envelope WoC 22cm Mix Matelasse Black GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('556', null, 'YSL Envelope WoC 22cm Mix Matelasse Beige GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('557', null, 'YSL Envelope Clutch Vert Khaki Grained', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('558', null, 'YSL Medium Monogramme Niki Shoulder Bag in Grey Khaki', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('559', null, 'BV The Chain Pouch in Seagrass GHW', '0', '2', '6', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('560', null, 'MOSCHINO Women Logo Platform Pool Slides in Black [39]', '0', '6', '36', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('561', null, 'YSL Small Loulou in Taupe', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('562', null, 'YSL Loulou Puffer Mini Beige GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('563', null, 'YSL Loulou Puffer Small Black GHW', '0', '2', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('564', null, 'CELINE Pico Belt Bag Light Taupe', '0', '2', '9', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('565', null, 'CELINE Pico Belt Bag Grey', '0', '2', '9', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('566', null, 'DIOR Etoile Ring', '0', '1', '15', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('567', null, 'FENDI FF Logo Bifold Wallet', '0', '16', '17', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('568', null, 'VALENTINO Vlogo Leather WoC with Handle Black', '0', '4', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('569', null, 'VALENTINO VLogo Double Strap Belt 3cm Black White Tan [75]', '0', '4', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('570', null, 'GIVENCHY Antigona Small Cloud Grey Smooth Leather', '0', '2', '19', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('571', null, 'FENDI FF Logo WoC', '0', '4', '17', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('572', null, 'BALENCIAGA Mini Edge Blanc GHW', '0', '2', '3', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('573', null, 'KENZO Bumbag Logo Cross Regular Taupe', '0', '2', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('574', null, 'TB Wallet Trifold Black GHW', '0', '16', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('575', null, 'TB Robinson Card Case Black', '0', '16', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('576', null, 'TB Robinson Card Case Grey GHW', '0', '16', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('577', null, 'TB All Black Thong [36]', '0', '6', '42', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('578', null, 'BALENCIAGA Small Graffiti Dark Grey', '0', '2', '3', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('579', null, 'VALENTINO VLOGO Signature Earrings in Metal and Swarovski', '0', '1', '43', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('580', null, 'KENZO Bumbag Regular Tiger Sand', '0', '2', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('581', null, 'KENZO Small Kenzogram Bucket Bag in Black with Shoulder Strap', '0', '2', '27', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('582', null, 'LC Le Pliage Expandable Travel Bag Cognac', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('583', null, 'MANOLO BLAHNIK Hangisi Pump 7cm in Black with Black Crystal [35]', '0', '6', '31', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('584', null, 'FURLA Lipari S Bucket Bag Beige', '0', '2', '18', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('585', null, 'LC Le Pliage Paris Saint Tropez Bucket Bag Orange', '0', '2', '29', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('586', null, 'YSL Uptown Pouch Croc Stamp Black SHW', '0', '11', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('587', null, 'YSL Kate Medium Shoulder Bag in Black with Tassel GHW', '0', '4', '44', null, null, null, '0', '0', '0', null, null, null, null);
INSERT INTO `products` VALUES ('588', null, 'VALENTINO Vlogo card holder', '0', '16', '43', null, null, null, '0', '0', '0', null, null, null, null);
